let products = [{
    id: "a",
    name: "Pizza Magharita",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 8.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "b",
    name: "Pizza Hot",
    incredidents: "mit scharfer Tomatensauce, Peperonisalami und herzhaften Gouda",
    price: 13.99,
    image: 'img/PizzaSalami.jpg',
    size: "26 cm",
},
{
    id: "c",
    name: "Pizza Brötchen",
    incredidents: "mit Tomatensauce und herzhaften Gouda und Knoblauchdressing",
    price: 5.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "d",
    name: "Pizza Gyros",
    incredidents: "mit Tomatensauce, Tzatziki, Gyros und herzhaften Gouda",
    price: 12.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "e",
    name: "Pizza Meatlover",
    incredidents: "mit Tomatensauce, viel Fleisch und herzhaften Gouda",
    price: 15.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "f",
    name: "Pizza Hollondaise",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 11.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "g",
    name: "Pizza des Monats",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 9.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "h",
    name: "Chefsalat",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 5.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "i",
    name: "Pizzabox",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 11.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "j",
    name: "Wasser",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 2.49,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "k",
    name: "Softdrinks",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 2.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
{
    id: "l",
    name: "Wein",
    incredidents: "mit Tomatensauce und herzhaften Gouda",
    price: 7.99,
    image: 'img/pizzaMagarita.jpg',
    size: "26 cm",
},
];